# Generated by Django 3.1.2 on 2020-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeatil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=300, unique=True)),
                ('enroll_no', models.IntegerField(error_messages={'unique': 'A user with that Enroll Number already exists.'}, unique=True)),
                ('roll_no', models.IntegerField(error_messages={'unique': 'A user with that Roll Number already exists.'}, unique=True)),
                ('mobile', models.IntegerField()),
                ('photo', models.ImageField(upload_to='myprofile')),
            ],
        ),
    ]
